### ISSUE TITLE
jokr - Permit functions in router can be affected by Dos

### ISSUE THREAD

**Issue by sherlock-admin2** [sherlock-audit/2024-02-jala-swap-judging#177]
jokr

medium

# Permit functions in router can be affected by Dos

## Summary
`JalaRouter02` supports permit functions which can be affected by Dos making them unusable

## Vulnerability Detail
`JalaRouter02` supports ERC20 permit functionality by which users could spend the tokens by signing an approval off-chain. In `JalaRouter02.removeLiquidityWithPermit`, after the permit call is successful there is a call to `removeLiquidity`.

```solidity

    function removeLiquidityWithPermit(
        address tokenA,
        address tokenB,
        uint256 liquidity,
        uint256 amountAMin,
        uint256 amountBMin,
        address to,
        uint256 deadline,
        bool approveMax,
        uint8 v,
        bytes32 r,
        bytes32 s
    ) external virtual override returns (uint256 amountA, uint256 amountB) {
        address pair = JalaLibrary.pairFor(factory, tokenA, tokenB);
        uint256 value = approveMax ? type(uint).max : liquidity;
        IJalaPair(pair).permit(msg.sender, address(this), value, deadline, v, r, s);
        (amountA, amountB) = removeLiquidity(tokenA, tokenB, liquidity, amountAMin, amountBMin, to, deadline);
    }
```

But while the transactions for `removeLiquidityWithPermit` is in mempool, anyone could extract the signature parameters from the call to `frontrun` the txn with direct `permit` call.

This would indeed increase the approval for the user. But as the `permit` is already been used, the call to `IJalaPair(pair).permit` in `removeLiquidityWithPermit` will revert making whole txn revert. Thus making the victim not able to make successful call to `removeLiquidityWithPermit` to remove his liquidity using permit

The above case holds for all the following functions below which can be affected by Dos.
1. removeLiquidityWithPermit
2. removeLiquidityETHWithPermit
3. removeLiquidityETHWithPermitSupportingFeeOnTransferTokens

## Impact
Users will not be able to use the permit functions for important actions

## Code Snippet

https://github.com/sherlock-audit/2024-02-jala-swap/blob/main/jalaswap-dex-contract/contracts/JalaRouter02.sol#L150-L167

https://github.com/sherlock-audit/2024-02-jala-swap/blob/main/jalaswap-dex-contract/contracts/JalaRouter02.sol#L169-L185

https://github.com/sherlock-audit/2024-02-jala-swap/blob/main/jalaswap-dex-contract/contracts/JalaRouter02.sol#L202-L225

## References

https://www.trust-security.xyz/post/permission-denied

## Tool used

Manual Review

## Recommendation
Wrap the permit calls in a try catch block
```diff
- IJalaPair(pair).permit(msg.sender, address(this), value, deadline, v, r, s);
+ try IJalaPair(pair).permit(msg.sender, address(this), value, deadline, v, r, s) {
+    (amountToken, amountETH) = removeLiquidityETH(token, liquidity, amountTokenMin, amountETHMin, to, deadline);
+ }
+ catch {
+     if (IJalaPair(pair).allowane(msg.sender, address(this)) >=  value)
+         (amountToken, amountETH) = removeLiquidityETH(token, liquidity, amountTokenMin, amountETHMin, to, deadline);
+     else 
+         revert("permit failed")
+ }
```

**Comment by 0xSpearmint** [comment]
Since there is no implementation of the permit function, the front-running scenario described will never happen. Therefore this should be invalid

The following is from the Criteria for Issue Validity by sherlock https://docs.sherlock.xyz/audits/judging/judging

Future issues: Issues that result out of a future integration/implementation that was not mentioned in the docs/README or because of a future change in the code (as a fix to another issue) are not valid issues.

**Comment by nevillehuang** [comment]
@0xSpearmint See comments [here](https://github.com/sherlock-audit/2023-12-jojo-exchange-update-judging/issues/30#issuecomment-1936076314), could be duplicates but to me they are separate issues with separate fixes

**Comment by 0xSpearmint** [comment]
@nevillehuang I had a read through the comments there.

I still stand by the fact that with the codebase provided to watsons the described front-running scenario would NEVER take place, the protocol would have to fix a different issue ( permit lacks implementation ), before the front-running attack vector is even possible.

Based of the sherlock rules about future issues, how can this be valid?

**Comment by nevillehuang** [comment]
@0xSpearmint I suggest u read the last 2 comments and head of judging reply:

> In case the vulnerabilities are entirely unrelated, I believe it is fair to validate both of them. But assuming an incorrect fix to any other issue (as stated in the rules) invalidates the submission. If an issue assumes the system works as intended while it doesn't and the reason of the system not working as intended gives direct grounds for the issue being non-exploitable (I'll work on the exact language here) allows these issues to be considered duplicates.

I specifically validated this because I was the one that initiated the question regarding this type of issues

**Comment by 0xSpearmint** [comment]
@nevillehuang Thank you for your responses

I understand your point, and the lead judge's comments but I believe this specific situation is different so I would like further clarification from you and/or the head of judging if possible since there is an obvious violation of the Criteria for Issue Validity by sherlock

>Future issues: Issues that result out of a future integration/implementation that was not mentioned in the docs/README or because of a future change in the code (as a fix to another issue) are not valid issues.

For the front-running scenario to happen, it assumes an implementation of the permit function ( which does not exist ). Does sherlock expect watsons to find bugs on functions that are not implemented? From my perspective, the front-running vulnerability is hypothetical and outside the audit's scope.

I want to comment that, prioritizing issues based on speculative future implementations diverts watsons attention from existing vulnerabilities. This approach is inefficient, potentially leaving immediate security risks unaddressed. Any future implementation of the permit function would necessitate a new review, at which point potential vulnerabilities like front-running would be relevant and actionable.


Another point I want to raise for why this finding should be at least a low is that the proposed DOS is not severe enough to be classed a medium, if a user cannot withdraw using ```removeLiquidityWithPermit``` because it fails due to frontrunning, they can just use the normal ```removeLiquidity``` function to elicit the same outcome.

The following is from sherlock on how to classify DOS
>Could Denial-of-Service (DOS), griefing, or locking of contracts count as a Medium (or High) issue? DoS has two separate scores on which it can become an issue:

>1. The issue causes locking of funds for users for more than a week.

>2. The issue impacts the availability of time-sensitive functions (cutoff functions are not considered time-sensitive). If at least one of these are describing the case, the issue can be a Medium. If both apply, the issue can be considered of High severity. Additional constraints related to the issue may decrease its severity accordingly.
Griefing for gas (frontrunning a transaction to fail, even if can be done perpetually) is considered a DoS of a single block, hence only if the function is clearly time-sensitive, it can be a Medium severity issue.

Since the proposed DOS does NOT cause locked funds, does NOT impact a time sensitive function and has a simple workaround it should be low.

**Comment by cawfree** [comment]
Consider that the old [`GovernerBravo` implementation was susceptible to frontrunning](https://github.com/OpenZeppelin/openzeppelin-contracts/security/advisories/GHSA-5h3x-9wvq-w4m2) and attackers were able to prevent protocol admins from being able to upgrade their contracts. An attacker would _pay the gas fees_ to frontrun honest attempts to upgrade a protocol, because reliable attacker implementations would soft-lock the ability to upgrade, which would enable the  extortion of protocol owners.

In contrast, there's a perfectly valid workaround to the exploit described here. What's the point of the attacker building up the infrastructure and spending gas on this?

This is low severity.

**Comment by realfugazzi** [comment]
It's difficult to consider this more than a low given that frontrunning the permit doesn't enable any denial of service, the user can call the non-permit variant of the function. Attacker would just spend gas.

This concern has been around for quite some time (for example, see the implementation of SelfPermit in which allowance is checked before executing the permit call) and has come to attention recently due to a blog post. However, for the attack to be relevant it needs to create an actual DoS that would prevent access to some functionality, it makes no sense if there is another function that does exactly the same without the permit.

**Comment by mahmudoloyede** [comment]
This should have been escalated. This isn't a valid bug as stated by @0xSpearmint

**Comment by nevillehuang** [comment]
Sorry missed this discussion given no escalations was brought up, but I think I am inclined to agree with watsons, given there is a similar functionality to remove liquidity, unless there are intended integrations/use cases of removing liquidity with permit that makes it time sensitive.

**Comment by mahmudoloyede** [comment]
There are no intended integrations/use cases of removing liquidity with permit that makes it time sensitive (uniswapv2 has been using this same functionality for ages). The user can just call the regular remove liquidity function and they'll be good. It's difficult to consider this more than a low. This is even assuming the permit function was implemented, which isn't in this case.

**Comment by Czar102** [comment]
Indeed, this should definitely be a low severity issue.

**Comment by Czar102** [comment]
Despite there was no escalation, I'm planning to invalidate this issue.

**Comment by AuditorPraise** [comment]
the reported function doesn't exist in current codebase.
